Added Azure OpenAI support
weaviate/Verba pull request #67
Opened 2023-11-26 18:18 UTC by jcarme

- Azure OpenAI support both for embeddings and queries.
- Updates of the .env.example with comments for all requested configuration
- Added optional waiting time between queries. Required with Azure OpenAI as there are per-minute quotas. Configurable with .env.

2023-11-27 14:57 UTC, jcarme commented
Hello, I agree with the contributor licence agreement.

2023-11-29 10:37 UTC, thomashacker requested changes
Great work! There are some minor changes, but it looks good otherwise. One thing that would be great is a new passage in the README documenting on how to get the Azure keys and how to set them in the .env file. Also mention that these settings modify the existing GPT4Generator 🚀

2023-11-29 10:37 UTC, thomashacker commented on goldenverba/components/generation/GPT4Generator.py
> +            print(f"---{chat_completion_arguments}")
Is this still left from the debugging? 😄

2023-11-29 10:37 UTC, thomashacker commented on goldenverba/verba_manager.py
> +            if "OPENAI_API_TYPE" in os.environ:
We have these checks and assignments in two places now, I think it would be cleaner if we keep them in the `VerbaManager`

2023-11-29 10:38 UTC, thomashacker commented on goldenverba/verba_manager.py
> +            if "OPENAI_API_TYPE" in os.environ:
Maybe have a warning when the type is set to azure but the other environment variables are not set

2023-12-07 16:28 UTC, jcarme commented on goldenverba/verba_manager.py
> +            if "OPENAI_API_TYPE" in os.environ:
I tried to change it but the problem is that setup_client is called before verify_installed_libraries. So I am not sure how to handle that in a better way.

2023-12-15 10:35 UTC, thomashacker commented on goldenverba/verba_manager.py
> +            if "OPENAI_API_TYPE" in os.environ:
Then let's keep it that way for now, I wanted to do a rework on setting the API Keys anyway! Great work!

2023-12-15 10:36 UTC, thomashacker commented
Sorry for the long delays! I'll have a closer look and make sure we merge the PR! Thanks for the great work

2024-01-02 15:24 UTC, thomashacker approved these changes
Looks great!

2024-01-02 15:25 UTC, merged